version: "3"
services:
    nginx:
        restart: always
        build:
            context: ./nginx
            dockerfile: Dockerfile.dev
        ports:
            - "3050:80"
    api:
        build:
            context: ./server
            dockerfile: Dockerfile.dev
        ports:
            - "4000:4000"
            - "9229:9229"
        volumes:
            - /app/node_modules
            - ./server:/app
        environment:
            - NODE_ENV=development
            - PORT=4000
    client:
        build:
            context: ./client
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./client:/app
    mongo:
        container_name: mongo
        image: mongo
        command: mongod --bind_ip_all --replSet message
        ports:
            - "27017:27017"
    mongo_repl:
        container_name: mongo_repl
        image: mongo
        command: mongod --bind_ip_all --replSet message
        ports:
            - "27018:27017"
